name: home_widget
description: A plugin to provide a common interface for creating HomeScreen Widgets for Android and iOS.
version: 0.6.0
repository: https://github.com/ABausG/home_widget
funding:
  - https://github.com/sponsors/ABausG/
topics:
  - home-screen-widget
  - native
  - android
  - ios
screenshots:
  - description: 'iOS Counter HomeScreen Widget'
    path: pub/screenshots/ios-counter.gif
  - description: 'Android HomeScreen Widget'
    path: pub/screenshots/android.png

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: '>=3.3.9'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path_provider_foundation: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.0
  path_provider_platform_interface:
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: es.antonborri.home_widget
        pluginClass: HomeWidgetPlugin
      ios:
        pluginClass: HomeWidgetPlugin
